FROM centos:centos7

WORKDIR /work

ENV OSSIM_INSTALL_PREFIX=/usr/local \
    OSSIM_DATA=/data \
    OSSIM_PREFS_FILE=/usr/local/share/ossim/ossim-preferences-template \
    LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib \
    JAVA_HOME=/usr/lib/jvm/java \
    OSSIM_VERSION=1.9.0 \
    OSSIM_VERSION_TAG=SNAPSHOT \
    GROOVY_HOME=/work/groovy-3.0.13 \    
    PATH=/usr/gdal34/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# COPY ./build-kakadu.sh ./build-ossim.sh ./build-joms.sh ./apache-groovy-binary-3.0.13.zip /work/
# COPY ./ossim/ /work/ossim/
# COPY ./ossim-oms/ /work/ossim-oms/
# COPY ./ossim-plugins/ /work/ossim-plugins/
# COPY ./ossim-video/ /work/ossim-video/
# COPY ./ossim-private/ /work/ossim-private/
ADD ./dist/ /usr/local/

RUN echo "" \
    && useradd --uid 1001 --shell /usr/bin/bash omar \
    && chown -R omar:omar /usr/local \
    && yum install -y epel-release deltarpm \
                   https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm \
    && yum localinstall -y  --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm \                   
    && yum install -y \
        wget which java-11-openjdk  \
        gdal34 gdal34-python-tools libjpeg-turbo \
        ffmpeg  \
    && echo ""

USER omar
WORKDIR /home/omar

CMD bash
